// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrqrzscnnepfxkgyzovn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhycXJ6c2NubmVwZnhrZ3l6b3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NDU3NTUsImV4cCI6MjA2MzAyMTc1NX0.uvNCMykcoVtAJGM6PNgJas0qbNKt0Mymkx_DGR7aFxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);